### ISSUE TITLE
nodeFormat not working for Sankey Diagram

### ISSUE THREAD

**Issue by JulienBacquart** [highcharts-for-python/highcharts-core#148] opened 2024-03-05 15:42 UTC
**Describe the bug**
Whatever string format you specify for 'nodeFormat' for a tooltip in a Sankey Diagram, gets ignored and the result is always the same.
'pointFormat' works correctly.
Additionally 'valueSuffix' gets ignored for the node, but works correctly for the links.

**To Reproduce**
Minimal none working example:
```
from highcharts_core.chart import Chart

data = [{
        'from': 'France',
        'to': 'Portugal',
        'weight': 5,
    }
]

# Set chart options
options = {
    'chart': {
        'inverted': False,
    },
    'title': {
        'text': f"Title",
    },
    'subtitle': {
        'text': f"Subtitle",
    },
    'tooltip': {
        'headerFormat': 'null',
        'pointFormat': 'Working: {point.weight} Working',
        # Not working 
        'nodeFormat': '{point.name}: {point.sum} not Working!!!',
        # Not working for Node
        'valueSuffix': ' working_suffix'
    },
    'series': [{
        # 'nodes': nodes,
        'data': data,
        'type': 'sankey',
        'name': 'Sankey demo series',
    }],
}

my_chart = Chart(options = options)
my_chart.display()
```
![highcharts_bug](https://github.com/highcharts-for-python/highcharts-core/assets/16917004/a0687826-07a1-4927-8d6b-cd4fc5951d23)

**Expected behavior**
The 'nodeFormat' would have a behavior similar to 'pointFormat'.

**Your Environment:**
 - Windows 11
 - Python 3.11.7
 - Jupyter notebook Version: 7.0.6
 - highcharts-core Version: 1.5.1

**Comment by JulienBacquart** [comment] 2024-06-05 13:03
Hi,

I juste re-tested the minimal example provided with the latest version highcharts-core Version: 1.7.4 
And the problem is still present.

If I do:
```python
my_chart.to_js_literal()
```
'nodeFormat' is missing from the output.

**Comment by hcpchris** [comment] 2024-06-05 14:56
@JulienBacquart : Apologies for that - I've re-opened this ticket now and will be taking another look in that case. That issue should have been resolved back in v.1.6.0.

**Comment by hcpchris** [comment] 2024-06-08 04:08
@JulienBacquart : It turns out that it is working as expected. However, the issue is in your original code. The code you've included in the issue is specifying the tooltip at the level of the overall chart - `options.tooltip` - however the chart-level tooltip does not support the same set of options as the Sankey plot options or series level (`options.plot_options.sankey.tooltip` or `options.series[].tooltip`).

If you adjust the placement where you are specifying the tooltip, it works as expected:

```
from highcharts_core.chart import Chart

data = [{
        'from': 'France',
        'to': 'Portugal',
        'weight': 5,
    }
]

# Set chart options
options = {
    'chart': {
        'inverted': False,
    },
    'title': {
        'text': f"Title",
    },
    'subtitle': {
        'text': f"Subtitle",
    },
    'series': [{
        # 'nodes': nodes,
        'data': data,
        'type': 'sankey',
        'name': 'Sankey demo series',
        'tooltip': {
            'headerFormat': 'null',
            'pointFormat': 'Working: {point.weight} Working',
            # Not working 
            'nodeFormat': '{point.name}: {point.sum} not Working!!!',
            # Not working for Node
            'valueSuffix': ' working_suffix'
        },
    }],
}

my_chart = Chart(options = options)
my_chart.display()
```

The `nodeFormat` setting only applies to diagram tooltips like those used in `DependencyWheelSeries` and `SankeySeries`, thus you can use it in `DependencyWheelPlotOptions`, `DependencyWheelSeries`, `SankeyPlotOptions`, and `SankeySeries`.

I'll be closing this issue again, but if you have further questions feel free to comment here, re-open the issue, or report a new issue.

**Closed** 2024-06-08 04:09 UTC
Labels: bug

**Comment by JulienBacquart** [comment] 2024-06-11 08:27
@hcpchris,

I noticed that in the corrected example, the `valueSuffix` is working for the point but not for the node.
I got it working using the following code:
```python
            'nodeFormat': '{point.name}: {point.sum}{point.weight} not Working!!!',
```
`{point.sum}` return the correct value but without the correct suffix. 
`{point.weight}` return an empty value but with the correct suffix.
Put together it works, but I don't think it's the expected behavior.

**Comment by hcpchris** [comment] 2024-06-11 17:52
Thanks, @JulienBacquart ! I've created two new issues for those items you mention above. #181 relates to the `valueSuffix` issue while /highcharts-for-python-demos#10 relates to adding a demo for the Sankey diagram.

As a side note, I'll double check whether `keys` is properly implemented in Sankey series in Highcharts for Python. I believe that it should be, but if not then that's definitely a bug.
