### ISSUE TITLE
Highcharts for Python doesn't render in Jupyter

### ISSUE THREAD

**Issue by govinda18** [highcharts-for-python/highcharts-core#43] opened 2023-04-27 10:20 UTC
**Describe the bug**
Highcharts for python does not render in jupyter and throws an error:

Something went wrong with the Highcharts.js script. It should have been automatically loaded, but it did not load for over 3 seconds. Check your internet connection, and then if the problem persists please reach out for support.

**To Reproduce**
Create a venv with the following deps:
```
jupyterlab
highcharts-core
```

**Expected behavior**
Highcharts should render

**Your Environment:**
 - OS: Ubuntu 20
 - Python Version: 3.10
 - Highcharts JavaScript Version: 11

**Additional context**
The bug is in [this line](https://github.com/highcharts-for-python/highcharts-core/blob/master/highcharts_core/chart.py#L333). We are using js literal `new Highcharts.chart` but `Highcharts.chart` is not a constructor. A simple reproducer is in this fiddle: https://jsfiddle.net/tfy50bwg/. Removing the new works just fine.

**Comment by govinda18** [comment] 2023-04-27 10:32
Another thing I would mention here is that we should improve the javascript code [here](https://github.com/highcharts-for-python/highcharts-core/blob/master/highcharts_core/utility_functions.py#L396) as this does not show the error that occurred in console. For example, error #13 is not related to script not loading but container not found. It is not very apparent on what went wrong from the generic message.
It should add something like `console.error(err)` and the message should say something like `Please check browser console for more details.`

**Comment by hcpchris** [comment] 2023-04-27 12:17
Thanks, @govinda18 ! The issue with ``new`` seems to be something odd, since that code had been working fine prior to yesterday's release of Highcharts v.11. I'll have to see what is causing the ``new`` issue (no pun intended) to arise. Removing the ``new`` so far in my tests does not seem to be causing any conflicts or regression issues, so I expect to be able to release a patch update fixing the issue within the next few hours (same issue was identified in #42 ).

On your other suggestion to improve the error message handling, that's a very good suggestion. I'll include an improvement on that front in the patch release - might still need some further refinement, but at least something that provides a little clearer messaging will prove helpful.

I'm running through some CI/CD pipelines and tests currently, but I expect to have a patch released within the next several hours. This issue will get auto-closed as soon as the fixes are merged into the ``master`` branch, which should be about 1 - 2 minutes before version 1.1.1 is released to PyPi.

**Closed** 2023-04-27 13:58 UTC
Labels: bug
